spring:
    ai:
      openai:
        api-key: ${SPRING_AI_OPENAI_API_KEY}
        embedding:
          options:
            model: text-embedding-3-small
      vectorstore:
        qdrant:
          collection-name: GameRules
logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: http